"""catalogo componente flexible

Revision ID: 265367362cd9
Revises: f0b73abc4cc0
Create Date: 2026-07-16 16:50:18.656828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '265367362cd9'
down_revision: Union[str, None] = 'f0b73abc4cc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

tipo_componente_enum = postgresql.ENUM(
    'INTERRUPTOR_PRINCIPAL', 'SECCIONAL_TERMOMAGNETICO', 'SECCIONAL_DIFERENCIAL', name='tipo_componente'
)
proveedor_enum = postgresql.ENUM('ABB', 'OTRO', name='proveedor')


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalogo_componente', sa.Column('codigo_comercial', sa.String(length=100), nullable=True))
    op.add_column('catalogo_componente', sa.Column('categoria_path', sa.JSON(), nullable=False))
    op.add_column('catalogo_componente', sa.Column('categoria_raiz', sa.String(length=255), nullable=False))
    op.add_column('catalogo_componente', sa.Column('unidad', sa.String(length=20), nullable=False))
    op.add_column('catalogo_componente', sa.Column('precio_lista', sa.Numeric(precision=12, scale=4), nullable=True))
    op.add_column('catalogo_componente', sa.Column('precio_neto', sa.Numeric(precision=12, scale=4), nullable=True))
    op.add_column('catalogo_componente', sa.Column('atributos', sa.JSON(), nullable=True))
    op.add_column('catalogo_componente', sa.Column('archivo_origen', sa.String(length=500), nullable=False))
    op.add_column('catalogo_componente', sa.Column('fila_origen', sa.Integer(), nullable=False))
    op.alter_column('catalogo_componente', 'proveedor',
               existing_type=postgresql.ENUM('ABB', 'OTRO', name='proveedor'),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('catalogo_componente', 'descripcion',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000),
               existing_nullable=False)
    op.drop_index('ix_catalogo_componente_codigo', table_name='catalogo_componente')
    op.create_index(op.f('ix_catalogo_componente_categoria_raiz'), 'catalogo_componente', ['categoria_raiz'], unique=False)
    op.create_unique_constraint('uq_catalogo_componente_proveedor_codigo', 'catalogo_componente', ['proveedor', 'codigo'])
    op.drop_column('catalogo_componente', 'tipo')
    op.drop_column('catalogo_componente', 'corriente_nominal_a')
    op.drop_column('catalogo_componente', 'polos')
    op.drop_column('catalogo_componente', 'ancho_mm')
    op.drop_column('catalogo_componente', 'capacidad_corte_ka')
    op.drop_column('catalogo_componente', 'alto_mm')
    op.drop_column('catalogo_componente', 'precio_vigente')
    tipo_componente_enum.drop(op.get_bind(), checkfirst=True)
    proveedor_enum.drop(op.get_bind(), checkfirst=True)
    op.alter_column('catalogo_precio_historial', 'precio_anterior',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=12, scale=4),
               existing_nullable=False)
    op.alter_column('catalogo_precio_historial', 'precio_nuevo',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=12, scale=4),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('catalogo_precio_historial', 'precio_nuevo',
               existing_type=sa.Numeric(precision=12, scale=4),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)
    op.alter_column('catalogo_precio_historial', 'precio_anterior',
               existing_type=sa.Numeric(precision=12, scale=4),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)
    tipo_componente_enum.create(op.get_bind(), checkfirst=True)
    proveedor_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('catalogo_componente', sa.Column('precio_vigente', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))
    op.add_column('catalogo_componente', sa.Column('alto_mm', sa.NUMERIC(precision=8, scale=2), autoincrement=False, nullable=False))
    op.add_column('catalogo_componente', sa.Column('capacidad_corte_ka', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=False))
    op.add_column('catalogo_componente', sa.Column('ancho_mm', sa.NUMERIC(precision=8, scale=2), autoincrement=False, nullable=False))
    op.add_column('catalogo_componente', sa.Column('polos', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('catalogo_componente', sa.Column('corriente_nominal_a', sa.NUMERIC(precision=8, scale=2), autoincrement=False, nullable=False))
    op.add_column('catalogo_componente', sa.Column('tipo', postgresql.ENUM('INTERRUPTOR_PRINCIPAL', 'SECCIONAL_TERMOMAGNETICO', 'SECCIONAL_DIFERENCIAL', name='tipo_componente'), autoincrement=False, nullable=False))
    op.drop_constraint('uq_catalogo_componente_proveedor_codigo', 'catalogo_componente', type_='unique')
    op.drop_index(op.f('ix_catalogo_componente_categoria_raiz'), table_name='catalogo_componente')
    op.create_index('ix_catalogo_componente_codigo', 'catalogo_componente', ['codigo'], unique=True)
    op.alter_column('catalogo_componente', 'descripcion',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
    op.alter_column('catalogo_componente', 'proveedor',
               existing_type=sa.String(length=100),
               type_=postgresql.ENUM('ABB', 'OTRO', name='proveedor'),
               existing_nullable=False)
    op.drop_column('catalogo_componente', 'fila_origen')
    op.drop_column('catalogo_componente', 'archivo_origen')
    op.drop_column('catalogo_componente', 'atributos')
    op.drop_column('catalogo_componente', 'precio_neto')
    op.drop_column('catalogo_componente', 'precio_lista')
    op.drop_column('catalogo_componente', 'unidad')
    op.drop_column('catalogo_componente', 'categoria_raiz')
    op.drop_column('catalogo_componente', 'categoria_path')
    op.drop_column('catalogo_componente', 'codigo_comercial')
    # ### end Alembic commands ###
