"""add_accesorios_y_armado

Revision ID: 875d8ceb47c9
Revises: 9a8b7c6d5e4f
Create Date: 2026-07-21 17:56:00.183763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '875d8ceb47c9'
down_revision: Union[str, None] = '9a8b7c6d5e4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regla_cablecanal',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('corriente_minima', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('corriente_maxima', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('medida_cablecanal', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tablero_accesorio_principal',
    sa.Column('tablero_id', sa.UUID(), nullable=False),
    sa.Column('componente_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['componente_id'], ['catalogo_componente.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tablero_id'], ['tablero.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tablero_id', 'componente_id')
    )
    op.add_column('tablero', sa.Column('principal_metodo_entrada', sa.String(length=50), nullable=True, server_default='cable'))
    op.add_column('tablero', sa.Column('principal_metodo_salida', sa.String(length=50), nullable=True, server_default='barra_distribucion'))
    op.add_column('tablero', sa.Column('borneras_tipo', sa.String(length=50), nullable=True, server_default='ninguno'))
    op.add_column('tablero', sa.Column('lleva_banquitos', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tablero', 'lleva_banquitos')
    op.drop_column('tablero', 'borneras_tipo')
    op.drop_column('tablero', 'principal_metodo_salida')
    op.drop_column('tablero', 'principal_metodo_entrada')
    op.drop_table('tablero_accesorio_principal')
    op.drop_table('regla_cablecanal')
    # ### end Alembic commands ###
