"""add_reglas_construccion

Revision ID: a2ab3748ca26
Revises: 875d8ceb47c9
Create Date: 2026-07-23 10:18:28.445303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2ab3748ca26'
down_revision: Union[str, None] = '875d8ceb47c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parametro_calculo', sa.Column('factor_llenado_cablecanal', sa.Numeric(precision=3, scale=2), nullable=False, server_default='0.65'))
    op.add_column('seccion', sa.Column('paso_mm', sa.Integer(), nullable=False, server_default='150'))
    op.add_column('seccion', sa.Column('paso_manual', sa.Integer(), nullable=True))
    op.add_column('tablero', sa.Column('porcentaje_reserva', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('tablero', sa.Column('gabinete_sugerido_id', sa.UUID(), nullable=True))
    op.add_column('tablero', sa.Column('distribuidor_sugerido_id', sa.UUID(), nullable=True))
    op.add_column('tablero', sa.Column('cablecanal_sugerido', sa.String(length=50), nullable=True))
    op.create_foreign_key('fk_tablero_distribuidor_sugerido', 'tablero', 'catalogo_componente', ['distribuidor_sugerido_id'], ['id'])
    op.create_foreign_key('fk_tablero_gabinete_sugerido', 'tablero', 'catalogo_componente', ['gabinete_sugerido_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_tablero_distribuidor_sugerido', 'tablero', type_='foreignkey')
    op.drop_constraint('fk_tablero_gabinete_sugerido', 'tablero', type_='foreignkey')
    op.drop_column('tablero', 'cablecanal_sugerido')
    op.drop_column('tablero', 'distribuidor_sugerido_id')
    op.drop_column('tablero', 'gabinete_sugerido_id')
    op.drop_column('tablero', 'porcentaje_reserva')
    op.drop_column('seccion', 'paso_manual')
    op.drop_column('seccion', 'paso_mm')
    op.drop_column('parametro_calculo', 'factor_llenado_cablecanal')
    # ### end Alembic commands ###
