"""add_global_paso_to_tablero

Revision ID: a7899bc84f21
Revises: a2ab3748ca26
Create Date: 2026-07-23 11:59:35.804933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7899bc84f21'
down_revision: Union[str, None] = 'a2ab3748ca26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tablero', sa.Column('paso_mm', sa.Integer(), server_default='150', nullable=False))
    op.add_column('tablero', sa.Column('paso_manual', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tablero', 'paso_manual')
    op.drop_column('tablero', 'paso_mm')
    # ### end Alembic commands ###
