"""esquema inicial

Revision ID: f0b73abc4cc0
Revises: 
Create Date: 2026-07-16 11:14:26.512571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0b73abc4cc0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalogo_componente',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.String(length=100), nullable=False),
    sa.Column('proveedor', sa.Enum('ABB', 'OTRO', name='proveedor'), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=False),
    sa.Column('tipo', sa.Enum('INTERRUPTOR_PRINCIPAL', 'SECCIONAL_TERMOMAGNETICO', 'SECCIONAL_DIFERENCIAL', name='tipo_componente'), nullable=False),
    sa.Column('polos', sa.Integer(), nullable=False),
    sa.Column('corriente_nominal_a', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('capacidad_corte_ka', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('ancho_mm', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('alto_mm', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('precio_vigente', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('vigente_desde', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalogo_componente_codigo'), 'catalogo_componente', ['codigo'], unique=True)
    op.create_table('usuario',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.Enum('ANALISTA', 'SUPERVISOR', name='rol_usuario'), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuario_email'), 'usuario', ['email'], unique=True)
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('accion', sa.String(length=255), nullable=False),
    sa.Column('entidad', sa.String(length=100), nullable=False),
    sa.Column('entidad_id', sa.String(length=100), nullable=False),
    sa.Column('detalle', sa.JSON(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('catalogo_precio_historial',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('componente_id', sa.UUID(), nullable=False),
    sa.Column('precio_anterior', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('precio_nuevo', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['componente_id'], ['catalogo_componente.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proyecto',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cliente', sa.String(length=255), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('analista_id', sa.UUID(), nullable=False),
    sa.Column('estado', sa.Enum('EN_CURSO', 'FINALIZADO', 'CANCELADO', name='estado_proyecto'), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analista_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('extraccion_cad',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('proyecto_id', sa.UUID(), nullable=False),
    sa.Column('archivo_nombre', sa.String(length=500), nullable=False),
    sa.Column('archivo_ruta', sa.String(length=1000), nullable=False),
    sa.Column('resultado_crudo', sa.JSON(), nullable=True),
    sa.Column('estado', sa.Enum('PENDIENTE', 'PROCESANDO', 'PENDIENTE_REVISION', 'CONFIRMADO', 'ERROR', name='estado_extraccion'), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyecto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tablero',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('proyecto_id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('interruptor_principal_id', sa.UUID(), nullable=True),
    sa.Column('nivel_falla_ka', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['interruptor_principal_id'], ['catalogo_componente.id'], ),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyecto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bom_linea',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tablero_id', sa.UUID(), nullable=False),
    sa.Column('componente_id', sa.UUID(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario_congelado', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['componente_id'], ['catalogo_componente.id'], ),
    sa.ForeignKeyConstraint(['tablero_id'], ['tablero.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seccion',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tablero_id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tablero_id'], ['tablero.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('salida',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('seccion_id', sa.UUID(), nullable=False),
    sa.Column('carga_valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('carga_unidad', sa.String(length=10), nullable=False),
    sa.Column('formato', sa.Enum('UNIPOLAR', 'BIPOLAR', 'TETRAPOLAR', name='formato_polos'), nullable=False),
    sa.Column('componente_id', sa.UUID(), nullable=True),
    sa.Column('origen', sa.Enum('MANUAL', 'IA_PENDIENTE', 'IA_CONFIRMADA', name='origen_salida'), nullable=False),
    sa.Column('posicion_orden', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['componente_id'], ['catalogo_componente.id'], ),
    sa.ForeignKeyConstraint(['seccion_id'], ['seccion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('salida')
    op.drop_table('seccion')
    op.drop_table('bom_linea')
    op.drop_table('tablero')
    op.drop_table('extraccion_cad')
    op.drop_table('proyecto')
    op.drop_table('catalogo_precio_historial')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_usuario_email'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_index(op.f('ix_catalogo_componente_codigo'), table_name='catalogo_componente')
    op.drop_table('catalogo_componente')
    # ### end Alembic commands ###
